<?php

/**
 * Created by PhpStorm.
 * User: matao
 * Date: 2018/8/10
 * Time: 11:02
 */

namespace app\admin\controller;

use think\Controller;
use think\Request;

class Base extends Controller{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub



    }


}